package com.hashjosh.identity.enums;

public enum DesignatedType {
    FARMER_AGRICULTURE_COMMUNICATION,
    PCIC_AGRICULTURE_COMMUNICATION,
    FARMER_MARKET_ACCESS,
    FARMER_FINANCIAL_SERVICES,
    FARMER_INPUTS_ACCESS,
    FARMER_CLIMATE_RESILIENCE,
    AGRO_DEALER_INPUTS_SUPPLIER,
    AGRO_DEALER_MARKET_LINKAGES,
    AGRO_DEALER_FINANCIAL_SERVICES,
    LOGISTICS_PROVIDER_TRANSPORTATION,
    LOGISTICS_PROVIDER_WAREHOUSING,
    LOGISTICS_PROVIDER_DISTRIBUTION,
}
