spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/agripro_application
    username: agripro
    password: agripro
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  cookieName: jwt
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  expiration: 86400000

frontend:
  url: http://localhost:3000

server:
  port: 8020
