spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/communication
    username: agripro
    password: agripro
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    generate-ddl: false
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: communication-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: >
          newMessageEvent:com.hashjosh.kafkacommon.communication.NewMessageEvent,
          requestPasswordResetEvent:com.hashjosh.kafkacommon.user.RequestPasswordResetEvent


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

token:
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  access-token-expiration-ms: 14400000
  access-token-expiration-remember-me-ms: 2592000000
  refresh-token-expiration-ms: 86400000
  refresh-token-expiration-remember-me-ms: 345600000

trusted:
  internal-service-ids:
    - agriculture-service
    - notification-service
    - farmer-service
    - transaction-service
    - schedule-service
    - pcic-service
    - application-service
    - document-service
    - rsbsa-service
    - program-service

server:
  port: 9040