spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/agripro_users
    username: agripro
    password: agripro
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: pracullosjohnpaul@gmail.com
    password: vdhs xjtv fkqw eamc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
server:
  port: 8010
jwt:
  cookieName: jwt
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  expiration: 86400000
frontend:
  url: http://localhost:3000