multitenancy:
  defaultTenant: agriculture
  tenants:
    farmer:
      url: jdbc:postgresql://localhost:5432/farmer
      username: agripro
      password: agripro
      driverClassName: org.postgresql.Driver
    pcic:
      url: jdbc:postgresql://localhost:5432/pcic
      username: agripro
      password: agripro
      driverClassName: org.postgresql.Driver
    agriculture:
      url: jdbc:postgresql://localhost:5432/agriculture
      username: agripro
      password: agripro
      driverClassName: org.postgresql.Driver

spring:
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enable: false
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    contexts: dev

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: userRegistrationContract:com.hashjosh.kafkacommon.user.UserRegistrationContract
        spring.json.add.type.headers: true


token:
  secret: lJ43fZtwCfh2qNM0uFx3mHSYGh/qrfXUtrM4Vl/kiZE=
  accessTokenExpirationMs: 14400000                # 4 hours
  accessTokenExpirationRememberMeMs: 2592000000    # 30 days
  refreshTokenExpirationMs: 86400000               # 1 day
  refreshTokenExpirationRememberMeMs: 345600000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true


management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

server:
  port: 8030



