### Login request
POST http://localhost:9000/api/v1/auth/login
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json

{
  "username": "pracullosdeo28",
  "password": "123456789",
  "rememberMe": false
}


### Get authenticated user
GET http://localhost:9000/api/v1/auth/me
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Accept: application/json


### Get all users
GET http://localhost:9000/api/v1/users
Accept: application/json
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36




#### Create application type
POST http://localhost:9000/api/v1/application/types
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json

{
  "name": "Application  1",
  "description": "application 1",
  "layout": "layout1",
  "sections": [
    {
      "title": "Basic information",
      "fields": [
        {
          "key": "age",
          "fieldName": "Age",
          "fieldType": "number",
          "required": true
        },
        {
          "key": "name",
          "fieldName": "Name",
          "fieldType": "text",
          "required": true
        }
      ]
    },
    {
      "title": "Crop Information",
      "fields": [
        {
          "key": "crop_types",
          "fieldName": "Type of crop",
          "fieldType": "text",
          "required": true
        }
      ]
    }
  ]
}

### Get Application
GET http://localhost:9000/api/v1/application/types
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Content-Type: application/json
Accept: application/json



#### Submit application type
POST http://localhost:9000/api/v1/applications/eb6566db-f83a-4385-97db-31a01c707e54/submit
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Content-Type: multipart/form-data
Accept: application/json

--form
fieldValues={"age":25,"name":"Pedro Santos","crop_types":"Rice"}
files=null