spring:
  config:
    import: optional:configserver:http://config-server:8888
  application:
    name: discovery-server

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
