spring:
  profiles:
    default: default
    active: local
  application:
    name: application-service
  config:
    import: optional:configserver:http://localhost:8888

# File upload configuration

