package com.hashjosh.verification.enums;

public enum VerificationStatus {
    APPROVED_BY_ADJUSTER,
    PROCESSING_BY_ADJUSTER,
    VERIFIED_BY_ADJUSTER,
    REJECTED_BY_ADJUSTER,
    CANCELLED_BY_ADJUSTER,

    // Underwriter status
    APPROVED_BY_UNDERWRITER,
    PROCESSING_BY_UNDERWRITER,
    VERIFIED_BY_UNDERWRITER,
    REJECTED_BY_UNDERWRITER,
    CANCELLED_BY_UNDERWRITER,


    APPROVED,
    VERIFIED,
    PENDING,
    CANCELLED,
    REJECTED,

    CANCELLED_BY_USER;
}
