spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/v1/users/**,/api/v1/auth/**,/api/v1/roles/**,/api/v1/authorities/**
            - id: application-service
              uri: lb://application-service
              predicates:
                - Path=/api/v1/applications/**,/api/v1/application/types/**,/api/v1/application/fields/**,/api/v1/application/sections/**,

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
