spring:
  application:
    name: application-service
  config:
    import: optional:configserver:http://config-server:8888
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
